### ISSUE TITLE
Golem not selling item "Heat Ray"

### ISSUE THREAD

**Issue by Cosmoledo** [Rijam/BossesAsNPCs#1]
Hey, I noticed that the Golem does not sell the [Heat Ray ](https://terraria.fandom.com/wiki/Heat_Ray) in version 1.4.4, but it should and  does so in [1.4.3](https://github.com/Rijam/BossesAsNPCs/blob/1.4.3/NPCs/SetupShops.cs#L2362).

Please add it back in.

Thank you :D

**Comment by Rijam** [comment]
Whoops. Fixed in the next version. That means Golem hasn't sold the Heat Ray in over a year lol.

Also, please use the correct Terraria wiki https://terraria.wiki.gg/wiki/Heat_Ray

**Comment by Rijam** [comment]
Fixed in version 0.2.9 https://github.com/Rijam/BossesAsNPCs/releases/tag/v0.2.9
